name = "python-example"
version = "0.1.0"
description = "Example of a plugin written in Python"
home = "https://github.com/stencila/plugin-example-python"
install = "git+https://github.com/stencila/plugin-example-python"
runtime = "python>=3.9"
transports = ["stdio", "http"]
command = "run_plugin"

[[kernels]]
name = "Example"
